<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.ClientFactory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Booking.Application\Booking.Application.csproj" />
    <ProjectReference Include="..\Booking.Persistence\Booking.Persistence.csproj" />
    <ProjectReference Include="..\..\..\shared\ParkingSystem.Contracts\ParkingSystem.Contracts.csproj" />
    <ProjectReference Include="..\..\..\grpc_proto\ParkingSystem.Grpc.csproj" />
  </ItemGroup>

</Project>
