<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Notification.Application\Notification.Application.csproj" />
    <ProjectReference Include="..\Notification.Persistence\Notification.Persistence.csproj" />
    <ProjectReference Include="..\..\..\shared\ParkingSystem.Contracts\ParkingSystem.Contracts.csproj" />
  </ItemGroup>

</Project>
