<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\contracts\ParkingSystem.Contracts\ParkingSystem.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\ParkingSystem.ServiceDefaults\ParkingSystem.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
