//------------------------------------------------------------------------------
// <auto-generated>
//     Strongly typed accessors for Resources.resx.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Booking.Application;

using System.Globalization;
using System.Resources;

public class Resources
{
    private static ResourceManager? resourceManager;

    internal Resources()
    {
    }

    public static ResourceManager ResourceManager => resourceManager ??= new ResourceManager("Booking.Application.Resources", typeof(Resources).Assembly);

    public static CultureInfo? Culture { get; set; }

    public static string CommonErrorMessage => ResourceManager.GetString("CommonErrorMessage", Culture) ?? string.Empty;

    public static string NotImplementedExceptionMessage => ResourceManager.GetString("NotImplementedExceptionMessage", Culture) ?? string.Empty;

    public static string DbUpdateExceptionMessage => ResourceManager.GetString("DbUpdateExceptionMessage", Culture) ?? string.Empty;

    public static string UnexpectedErrorMessage => ResourceManager.GetString("UnexpectedErrorMessage", Culture) ?? string.Empty;

    public static string UnauthorizedMessage => ResourceManager.GetString("UnauthorizedMessage", Culture) ?? string.Empty;

    public static string ForbiddenMessage => ResourceManager.GetString("ForbiddenMessage", Culture) ?? string.Empty;

    public static string LotAvailabilityRetrieved => ResourceManager.GetString("LotAvailabilityRetrieved", Culture) ?? string.Empty;

    public static string ParkingServiceUnavailable => ResourceManager.GetString("ParkingServiceUnavailable", Culture) ?? string.Empty;

    public static string LotIdIsRequired => ResourceManager.GetString("LotIdIsRequired", Culture) ?? string.Empty;

}
